%% 舰艇/潜艇水压场时间动态仿真
% 本脚本读取 C++ 仿真生成的水压场 CSV，动态显示压力曲线和目标位置。
% 兼容 MATLAB R2017a/R2017b，不使用 sgtitle、xline、yline 等新版本函数。

clear;
clc;
close all;

%% 一、记录本次仿真的基本参数
% 以下参数与 main.cpp 中生成 pressure_field_time_series.csv 的示例工况一致。
% 如果重新生成 CSV 时修改了 C++ 参数，应同步修改本节，避免动画说明与数据不一致。
simulationParameters.targetType = '水面舰艇';                  % 目标类型。
simulationParameters.lengthM = 100.0;                         % 舰长 L，单位 m。
simulationParameters.widthM = 15.0;                           % 舰宽 B，单位 m。
simulationParameters.draftM = 5.0;                            % 吃水 T，单位 m。
simulationParameters.waterDepthM = 60.0;                      % 海深 H，单位 m。
simulationParameters.velocityMps = 3.0;                       % 低速航速 U，单位 m/s。
simulationParameters.initialPositionM = [-180.0, 40.0, -2.5]; % 零时刻舰艇中心坐标，单位 m。
simulationParameters.headingDegrees = 0.0;                    % 航向角，0°表示沿 x 轴正方向航行。
simulationParameters.waterDensityKgM3 = 1025.0;               % 海水密度，单位 kg/m^3。
simulationParameters.gravityMps2 = 9.80665;                   % 重力加速度，单位 m/s^2。
simulationParameters.blockCoefficient = 0.68;                 % 方形系数 Cb。
simulationParameters.minimumDistanceM = 1.0;                  % 偶极子模型最小适用距离，单位 m。
simulationParameters.sensorPositionM = [0.0, 0.0, -55.0];     % 固定水压传感器坐标，单位 m。
simulationParameters.startTimeS = 0.0;                        % 仿真开始时间，单位 s。
simulationParameters.durationS = 75.0;                        % 仿真持续时间，单位 s。
simulationParameters.sampleRateHz = 20.0;                     % 采样率，单位 Hz。

% 等效排水体积由方形系数和舰艇长、宽、吃水共同确定。
simulationParameters.displacementVolumeM3 = ...
    simulationParameters.blockCoefficient * ...
    simulationParameters.lengthM * ...
    simulationParameters.widthM * ...
    simulationParameters.draftM;

%% 二、读取水压场仿真结果
% 脚本放在项目根目录，因此使用脚本路径自动定位 CSV 文件。
scriptPath = mfilename('fullpath');
projectRoot = fileparts(scriptPath);
pressureFile = fullfile(projectRoot, 'pressure_field_time_series.csv');

if exist(pressureFile, 'file') ~= 2
    error(['找不到水压场结果文件：%s\n' ...
        '请先运行 seamine_simulator 生成该文件。'], pressureFile);
end

pressureData = readtable(pressureFile);

if isempty(pressureData)
    error('水压场结果文件中没有可绘制的数据。');
end

%% 三、设置动态播放参数
% 1 表示按真实仿真时间播放，10 表示十倍速播放。
playbackSpeed = 10.0;

% 当前数据为 20 Hz、十倍速播放，每 10 个采样点刷新一次约对应 20 帧/秒。
% 压力数据仍逐点加入曲线，只减少界面重绘次数，不会丢失仿真数据。
refreshInterval = 10;

%% 四、在命令行输出完整仿真参数
fprintf('\n========== 水压场动画基本参数 ==========\n');
fprintf('目标类型：%s\n', simulationParameters.targetType);
fprintf('舰艇尺寸：L=%.3f m，B=%.3f m，T=%.3f m\n', ...
    simulationParameters.lengthM, ...
    simulationParameters.widthM, ...
    simulationParameters.draftM);
fprintf('海深：%.3f m\n', simulationParameters.waterDepthM);
fprintf('航速：%.3f m/s，航向：%.3f°\n', ...
    simulationParameters.velocityMps, ...
    simulationParameters.headingDegrees);
fprintf('初始位置：(%.3f, %.3f, %.3f) m\n', ...
    simulationParameters.initialPositionM(1), ...
    simulationParameters.initialPositionM(2), ...
    simulationParameters.initialPositionM(3));
fprintf('传感器位置：(%.3f, %.3f, %.3f) m\n', ...
    simulationParameters.sensorPositionM(1), ...
    simulationParameters.sensorPositionM(2), ...
    simulationParameters.sensorPositionM(3));
fprintf('海水密度：%.3f kg/m^3，重力加速度：%.5f m/s^2\n', ...
    simulationParameters.waterDensityKgM3, ...
    simulationParameters.gravityMps2);
fprintf('方形系数：%.3f，等效排水体积：%.3f m^3\n', ...
    simulationParameters.blockCoefficient, ...
    simulationParameters.displacementVolumeM3);
fprintf('最小适用距离：%.3f m\n', ...
    simulationParameters.minimumDistanceM);
fprintf('仿真时间：%.3f～%.3f s，采样率：%.3f Hz\n', ...
    simulationParameters.startTimeS, ...
    simulationParameters.startTimeS + simulationParameters.durationS, ...
    simulationParameters.sampleRateHz);
fprintf('播放速度：%.3f 倍\n', playbackSpeed);
fprintf('========================================\n');

%% 五、计算坐标轴范围和压力峰值
maximumPressure = max(abs(pressureData.dynamic_pressure_pa));
if ~isfinite(maximumPressure) || maximumPressure <= 0.0
    maximumPressure = 1.0;
end

minimumTargetX = min([pressureData.target_x_m; ...
    pressureData.sensor_x_m]);
maximumTargetX = max([pressureData.target_x_m; ...
    pressureData.sensor_x_m]);
minimumTargetY = min([pressureData.target_y_m; ...
    pressureData.sensor_y_m]);
maximumTargetY = max([pressureData.target_y_m; ...
    pressureData.sensor_y_m]);

% 为航迹图增加边缘留白，避免目标贴在坐标轴边界。
xMargin = max(10.0, 0.05 * (maximumTargetX - minimumTargetX));
yMargin = max(10.0, 0.05 * (maximumTargetY - minimumTargetY));

%% 六、创建动态仿真窗口
animationFigure = figure( ...
    'Name', '舰艇/潜艇水压场时间动态仿真', ...
    'Color', 'w', ...
    'NumberTitle', 'off', ...
    'Position', [100, 60, 1200, 820]);

%% 七、创建动态压力时序子图
pressureAxes = subplot(2, 2, 1);
hold(pressureAxes, 'on');
grid(pressureAxes, 'on');

pressureLine = animatedline(pressureAxes, ...
    'Color', [0.0, 0.35, 0.85], ...
    'LineWidth', 1.6);

currentPressureMarker = plot(pressureAxes, ...
    pressureData.time_s(1), ...
    pressureData.dynamic_pressure_pa(1), ...
    'ro', ...
    'MarkerSize', 7, ...
    'MarkerFaceColor', 'r');

% MATLAB 2017 不支持 yline，使用普通直线绘制零压力参考线。
plot(pressureAxes, ...
    [pressureData.time_s(1), pressureData.time_s(end)], ...
    [0.0, 0.0], ...
    'k--', ...
    'LineWidth', 0.8, ...
    'HandleVisibility', 'off');
xlim(pressureAxes, ...
    [pressureData.time_s(1), pressureData.time_s(end)]);
ylim(pressureAxes, ...
    [-1.1 * maximumPressure, 1.1 * maximumPressure]);
xlabel(pressureAxes, '时间 / s');
ylabel(pressureAxes, '动态压力变化 / Pa');
title(pressureAxes, '固定水下位置的动态压力');

%% 八、创建目标航迹子图
trajectoryAxes = subplot(2, 2, 2);
hold(trajectoryAxes, 'on');
grid(trajectoryAxes, 'on');

% 灰色虚线表示目标完整规划航迹。
plot(trajectoryAxes, ...
    pressureData.target_x_m, ...
    pressureData.target_y_m, ...
    '--', ...
    'Color', [0.65, 0.65, 0.65], ...
    'LineWidth', 1.0);

% 蓝色实线表示已经驶过的航迹。
traveledLine = animatedline(trajectoryAxes, ...
    'Color', [0.0, 0.35, 0.85], ...
    'LineWidth', 1.8);

% 红色五角星表示固定水压传感器。
sensorMarker = plot(trajectoryAxes, ...
    pressureData.sensor_x_m(1), ...
    pressureData.sensor_y_m(1), ...
    'rp', ...
    'MarkerSize', 13, ...
    'MarkerFaceColor', 'r');

% 蓝色圆点表示目标当前水平位置。
targetMarker = plot(trajectoryAxes, ...
    pressureData.target_x_m(1), ...
    pressureData.target_y_m(1), ...
    'bo', ...
    'MarkerSize', 9, ...
    'MarkerFaceColor', 'b');

xlim(trajectoryAxes, ...
    [minimumTargetX - xMargin, maximumTargetX + xMargin]);
ylim(trajectoryAxes, ...
    [minimumTargetY - yMargin, maximumTargetY + yMargin]);
axis(trajectoryAxes, 'equal');
xlabel(trajectoryAxes, '东向位置 x / m');
ylabel(trajectoryAxes, '北向位置 y / m');
title(trajectoryAxes, '目标实时位置与传感器');
legend(trajectoryAxes, ...
    {'完整航迹', '已驶过航迹', '水压传感器', '目标当前位置'}, ...
    'Location', 'best');

%% 九、创建目标距离和总表压子图
distanceAxes = subplot(2, 2, 3);
hold(distanceAxes, 'on');
grid(distanceAxes, 'on');

distanceLine = animatedline(distanceAxes, ...
    'Color', [0.1, 0.6, 0.2], ...
    'LineWidth', 1.6);

xlim(distanceAxes, ...
    [pressureData.time_s(1), pressureData.time_s(end)]);
distanceMaximum = max(pressureData.distance_m);
if ~isfinite(distanceMaximum) || distanceMaximum <= 0.0
    distanceMaximum = 1.0;
end
ylim(distanceAxes, [0.0, 1.05 * distanceMaximum]);
xlabel(distanceAxes, '时间 / s');
ylabel(distanceAxes, '目标与传感器距离 / m');
title(distanceAxes, '目标距离随时间变化');

totalPressureAxes = subplot(2, 2, 4);
hold(totalPressureAxes, 'on');
grid(totalPressureAxes, 'on');

totalPressureLine = animatedline(totalPressureAxes, ...
    'Color', [0.65, 0.15, 0.75], ...
    'LineWidth', 1.6);

xlim(totalPressureAxes, ...
    [pressureData.time_s(1), pressureData.time_s(end)]);
minimumTotalPressure = min(pressureData.total_gauge_pressure_pa) / 1000.0;
maximumTotalPressure = max(pressureData.total_gauge_pressure_pa) / 1000.0;
totalPressureMargin = max(0.01, ...
    0.1 * (maximumTotalPressure - minimumTotalPressure));
ylim(totalPressureAxes, ...
    [minimumTotalPressure - totalPressureMargin, ...
    maximumTotalPressure + totalPressureMargin]);
xlabel(totalPressureAxes, '时间 / s');
ylabel(totalPressureAxes, '总表压 / kPa');
title(totalPressureAxes, '总表压随时间变化');

%% 十、准备动画窗口中的固定参数说明
parameterTitleLine1 = sprintf( ...
    '%s：L=%.1f m，B=%.1f m，T=%.1f m，H=%.1f m，U=%.1f m/s，Cb=%.2f', ...
    simulationParameters.targetType, ...
    simulationParameters.lengthM, ...
    simulationParameters.widthM, ...
    simulationParameters.draftM, ...
    simulationParameters.waterDepthM, ...
    simulationParameters.velocityMps, ...
    simulationParameters.blockCoefficient);
parameterTitleLine2 = sprintf( ...
    '初始位置=(%.1f, %.1f, %.1f) m，航向=%.1f°，传感器=(%.1f, %.1f, %.1f) m', ...
    simulationParameters.initialPositionM(1), ...
    simulationParameters.initialPositionM(2), ...
    simulationParameters.initialPositionM(3), ...
    simulationParameters.headingDegrees, ...
    simulationParameters.sensorPositionM(1), ...
    simulationParameters.sensorPositionM(2), ...
    simulationParameters.sensorPositionM(3));
parameterTitleLine3 = sprintf( ...
    '仿真时间=%.1f～%.1f s，采样率=%.1f Hz，等效排水体积=%.1f m^3', ...
    simulationParameters.startTimeS, ...
    simulationParameters.startTimeS + simulationParameters.durationS, ...
    simulationParameters.sampleRateHz, ...
    simulationParameters.displacementVolumeM3);

% 为顶部四行参数与实时状态说明留出空间。
set(pressureAxes, 'Position', [0.07, 0.53, 0.40, 0.29]);
set(trajectoryAxes, 'Position', [0.55, 0.53, 0.40, 0.29]);
set(distanceAxes, 'Position', [0.07, 0.08, 0.40, 0.29]);
set(totalPressureAxes, 'Position', [0.55, 0.08, 0.40, 0.29]);

% MATLAB 2017 不支持 sgtitle，创建可逐帧更新的图窗文本框。
parameterTextBox = annotation(animationFigure, ...
    'textbox', ...
    [0.03, 0.85, 0.94, 0.14], ...
    'String', {parameterTitleLine1, parameterTitleLine2, ...
    parameterTitleLine3, '正在准备动画……'}, ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'Interpreter', 'none');

%% 十一、循环播放全部仿真采样
sampleCount = height(pressureData);
for sampleIndex = 1:sampleCount
    % 用户关闭窗口后立即停止播放，避免继续访问失效图形对象。
    if ~ishghandle(animationFigure)
        break;
    end

    currentTime = pressureData.time_s(sampleIndex);
    currentDynamicPressure = ...
        pressureData.dynamic_pressure_pa(sampleIndex);

    % 更新动态压力、目标航迹、目标距离和总表压曲线。
    addpoints(pressureLine, currentTime, currentDynamicPressure);
    addpoints(traveledLine, ...
        pressureData.target_x_m(sampleIndex), ...
        pressureData.target_y_m(sampleIndex));
    addpoints(distanceLine, ...
        currentTime, pressureData.distance_m(sampleIndex));
    addpoints(totalPressureLine, ...
        currentTime, ...
        pressureData.total_gauge_pressure_pa(sampleIndex) / 1000.0);

    % 按设定间隔更新标记和标题，最后一个采样点强制刷新。
    isRefreshSample = mod(sampleIndex, refreshInterval) == 0 || ...
        sampleIndex == sampleCount;
    if isRefreshSample
        % 使用 set 写法兼容 MATLAB 2017 的图形句柄属性设置。
        set(currentPressureMarker, ...
            'XData', currentTime, ...
            'YData', currentDynamicPressure);
        set(targetMarker, ...
            'XData', pressureData.target_x_m(sampleIndex), ...
            'YData', pressureData.target_y_m(sampleIndex));

        % 总标题的前三行显示固定工况，最后一行显示当前动画状态。
        dynamicTitleLine = sprintf( ...
            ['仿真时刻：%.2f s    动态压力：%.3f Pa    ' ...
            '目标距离：%.2f m    播放速度：%.1f 倍'], ...
            currentTime, ...
            currentDynamicPressure, ...
            pressureData.distance_m(sampleIndex), ...
            playbackSpeed);
        set(parameterTextBox, ...
            'String', {parameterTitleLine1, parameterTitleLine2, ...
            parameterTitleLine3, dynamicTitleLine});
        drawnow;
    end

    % 根据 CSV 中真实采样间隔和播放倍速控制动画节奏。
    if sampleIndex < sampleCount
        sampleTimeInterval = ...
            pressureData.time_s(sampleIndex + 1) - currentTime;
        pause(max(0.0, sampleTimeInterval / playbackSpeed));
    end
end

%% 十二、播放完成后输出结果摘要
if ishghandle(animationFigure)
    [~, peakIndex] = max(abs(pressureData.dynamic_pressure_pa));
    fprintf('水压场动画播放完成。\n');
    fprintf('采样点数：%d\n', sampleCount);
    fprintf('动态压力绝对值峰值：%.6f Pa\n', ...
        pressureData.dynamic_pressure_pa(peakIndex));
    fprintf('峰值发生时刻：%.3f s\n', ...
        pressureData.time_s(peakIndex));
    fprintf('峰值时目标距离：%.3f m\n', ...
        pressureData.distance_m(peakIndex));
end
