%% 舰艇/潜艇水压场时序绘图
% 读取 C++ 仿真生成的水压场 CSV，并绘制压力特征和目标航迹。
% 兼容 MATLAB R2017a/R2017b，不使用 sgtitle、xline、yline 等新版本函数。

clear;
clc;
close all;

%% 一、记录本次仿真的基本参数
% 以下参数与 main.cpp 中生成 pressure_field_time_series.csv 的示例工况一致。
% 如果重新生成 CSV 时修改了 C++ 参数，应同步修改本节，避免图像说明与数据不一致。
simulationParameters.targetType = '水面舰艇';                  % 目标类型。
simulationParameters.lengthM = 100.0;                         % 舰长 L，单位 m。
simulationParameters.widthM = 15.0;                           % 舰宽 B，单位 m。
simulationParameters.draftM = 5.0;                            % 吃水 T，单位 m。
simulationParameters.waterDepthM = 60.0;                      % 海深 H，单位 m。
simulationParameters.velocityMps = 3.0;                       % 低速航速 U，单位 m/s。
simulationParameters.initialPositionM = [-180.0, 40.0, -2.5]; % 零时刻舰艇中心坐标，单位 m。
simulationParameters.headingDegrees = 0.0;                    % 航向角，0°表示沿 x 轴正方向航行。
simulationParameters.waterDensityKgM3 = 1025.0;               % 海水密度，单位 kg/m^3。
simulationParameters.gravityMps2 = 9.80665;                   % 重力加速度，单位 m/s^2。
simulationParameters.blockCoefficient = 0.68;                 % 方形系数 Cb。
simulationParameters.minimumDistanceM = 1.0;                  % 偶极子模型最小适用距离，单位 m。
simulationParameters.sensorPositionM = [0.0, 0.0, -55.0];     % 固定水压传感器坐标，单位 m。
simulationParameters.startTimeS = 0.0;                        % 仿真开始时间，单位 s。
simulationParameters.durationS = 75.0;                        % 仿真持续时间，单位 s。
simulationParameters.sampleRateHz = 20.0;                     % 采样率，单位 Hz。

% 等效排水体积由方形系数和舰艇长、宽、吃水共同确定。
simulationParameters.displacementVolumeM3 = ...
    simulationParameters.blockCoefficient * ...
    simulationParameters.lengthM * ...
    simulationParameters.widthM * ...
    simulationParameters.draftM;

%% 二、读取水压场结果
% 脚本放在项目根目录，因此可据此自动定位 CSV 文件。
scriptPath = mfilename('fullpath');
projectRoot = fileparts(scriptPath);
pressureFile = fullfile(projectRoot, 'pressure_field_time_series.csv');

if exist(pressureFile, 'file') ~= 2
    error('找不到水压场结果文件：%s', pressureFile);
end

pressureData = readtable(pressureFile);

%% 三、查找动态压力绝对值峰值
% 水雷目标特征检测通常关注去除静水基线后的动态压力。
[~, peakIndex] = max(abs(pressureData.dynamic_pressure_pa));

peakTime = pressureData.time_s(peakIndex);
peakPressure = pressureData.dynamic_pressure_pa(peakIndex);

%% 四、绘制动态压力时序
resultFigure = figure('Name', '运动目标水压场仿真结果', ...
    'Color', 'w', ...
    'Position', [100, 80, 1200, 780]);

dynamicPressureAxes = subplot(2, 2, 1);
plot(pressureData.time_s, ...
    pressureData.dynamic_pressure_pa, ...
    'b-', 'LineWidth', 1.5);
hold on;
plot(peakTime, peakPressure, ...
    'ro', 'MarkerFaceColor', 'r');
% MATLAB 2017 不支持 yline，使用普通直线绘制零压力参考线。
plot([pressureData.time_s(1), pressureData.time_s(end)], ...
    [0.0, 0.0], 'k--', 'LineWidth', 0.8);
grid on;
xlabel('时间 / s');
ylabel('动态压力变化 / Pa');
title('固定水下位置的动态压力时序');
legend('动态压力', '绝对值峰值', '零压力线', ...
    'Location', 'best');

%% 五、绘制总表压
% 总表压包含静水压力，因此单位转换为 kPa。
totalPressureAxes = subplot(2, 2, 2);
plot(pressureData.time_s, ...
    pressureData.total_gauge_pressure_pa / 1000.0, ...
    'LineWidth', 1.5);
grid on;
xlabel('时间 / s');
ylabel('总表压 / kPa');
title('静水压力与动态压力叠加结果');

%% 六、绘制目标航迹和传感器位置
trajectoryAxes = subplot(2, 2, 3);
plot(pressureData.target_x_m, ...
    pressureData.target_y_m, ...
    'b-', 'LineWidth', 1.5);
hold on;
plot(pressureData.sensor_x_m(1), ...
    pressureData.sensor_y_m(1), ...
    'rp', 'MarkerSize', 12, 'MarkerFaceColor', 'r');
axis equal;
grid on;
xlabel('东向位置 x / m');
ylabel('北向位置 y / m');
title('目标航迹与水压传感器位置');
legend('目标航迹', '水压传感器', 'Location', 'best');

%% 七、绘制压力空间通过特征
spatialPressureAxes = subplot(2, 2, 4);
plot(pressureData.longitudinal_offset_m, ...
    pressureData.dynamic_pressure_pa, ...
    'm-', 'LineWidth', 1.5);
hold on;
% MATLAB 2017 不支持 yline，使用普通直线绘制零压力参考线。
plot([min(pressureData.longitudinal_offset_m), ...
    max(pressureData.longitudinal_offset_m)], ...
    [0.0, 0.0], 'k--', 'LineWidth', 0.8);
grid on;
xlabel('目标纵向相对距离 / m');
ylabel('动态压力变化 / Pa');
title('动态压力随目标纵向距离变化');

%% 八、在图窗顶部显示本次仿真的基本工况
% 总标题只展示识别图像最需要的参数，避免参数过多挤压子图空间。
parameterTitleLine1 = sprintf( ...
    '%s：L=%.1f m，B=%.1f m，T=%.1f m，H=%.1f m，U=%.1f m/s，Cb=%.2f', ...
    simulationParameters.targetType, ...
    simulationParameters.lengthM, ...
    simulationParameters.widthM, ...
    simulationParameters.draftM, ...
    simulationParameters.waterDepthM, ...
    simulationParameters.velocityMps, ...
    simulationParameters.blockCoefficient);
parameterTitleLine2 = sprintf( ...
    '初始位置=(%.1f, %.1f, %.1f) m，航向=%.1f°，传感器=(%.1f, %.1f, %.1f) m', ...
    simulationParameters.initialPositionM(1), ...
    simulationParameters.initialPositionM(2), ...
    simulationParameters.initialPositionM(3), ...
    simulationParameters.headingDegrees, ...
    simulationParameters.sensorPositionM(1), ...
    simulationParameters.sensorPositionM(2), ...
    simulationParameters.sensorPositionM(3));
parameterTitleLine3 = sprintf( ...
    '仿真时间=%.1f～%.1f s，采样率=%.1f Hz，等效排水体积=%.1f m^3', ...
    simulationParameters.startTimeS, ...
    simulationParameters.startTimeS + simulationParameters.durationS, ...
    simulationParameters.sampleRateHz, ...
    simulationParameters.displacementVolumeM3);

% 为顶部参数说明留出空间，避免文本框遮挡子图标题。
set(dynamicPressureAxes, 'Position', [0.07, 0.55, 0.40, 0.29]);
set(totalPressureAxes, 'Position', [0.55, 0.55, 0.40, 0.29]);
set(trajectoryAxes, 'Position', [0.07, 0.09, 0.40, 0.29]);
set(spatialPressureAxes, 'Position', [0.55, 0.09, 0.40, 0.29]);

% MATLAB 2017 不支持 sgtitle，使用图窗文本框显示所有子图的总标题。
annotation(resultFigure, 'textbox', [0.03, 0.88, 0.94, 0.11], ...
    'String', {parameterTitleLine1, parameterTitleLine2, parameterTitleLine3}, ...
    'EdgeColor', 'none', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontWeight', 'bold', ...
    'FontSize', 10, ...
    'Interpreter', 'none');

%% 九、在命令行输出完整参数和峰值信息
fprintf('\n========== 水压场仿真基本参数 ==========\n');
fprintf('目标类型：%s\n', simulationParameters.targetType);
fprintf('舰艇尺寸：L=%.3f m，B=%.3f m，T=%.3f m\n', ...
    simulationParameters.lengthM, ...
    simulationParameters.widthM, ...
    simulationParameters.draftM);
fprintf('海深：%.3f m\n', simulationParameters.waterDepthM);
fprintf('航速：%.3f m/s，航向：%.3f°\n', ...
    simulationParameters.velocityMps, ...
    simulationParameters.headingDegrees);
fprintf('初始位置：(%.3f, %.3f, %.3f) m\n', ...
    simulationParameters.initialPositionM(1), ...
    simulationParameters.initialPositionM(2), ...
    simulationParameters.initialPositionM(3));
fprintf('传感器位置：(%.3f, %.3f, %.3f) m\n', ...
    simulationParameters.sensorPositionM(1), ...
    simulationParameters.sensorPositionM(2), ...
    simulationParameters.sensorPositionM(3));
fprintf('海水密度：%.3f kg/m^3，重力加速度：%.5f m/s^2\n', ...
    simulationParameters.waterDensityKgM3, ...
    simulationParameters.gravityMps2);
fprintf('方形系数：%.3f，等效排水体积：%.3f m^3\n', ...
    simulationParameters.blockCoefficient, ...
    simulationParameters.displacementVolumeM3);
fprintf('最小适用距离：%.3f m\n', ...
    simulationParameters.minimumDistanceM);
fprintf('仿真时间：%.3f～%.3f s，采样率：%.3f Hz\n', ...
    simulationParameters.startTimeS, ...
    simulationParameters.startTimeS + simulationParameters.durationS, ...
    simulationParameters.sampleRateHz);
fprintf('========================================\n');
fprintf('水压场采样点数：%d\n', height(pressureData));
fprintf('动态压力绝对值峰值：%.6f Pa\n', peakPressure);
fprintf('峰值发生时刻：%.3f s\n', peakTime);
fprintf('峰值时目标距离：%.3f m\n', ...
    pressureData.distance_m(peakIndex));
