%% 渲染当前舰艇磁场原理文档的 LaTeX 公式
% 每个公式输出为高分辨率 PNG，供 Word 构建脚本插入。

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));
outputDirectory = fullfile(projectRoot, 'build', 'docx_magnetic_principles', 'equations');
if exist(outputDirectory, 'dir') ~= 7
    mkdir(outputDirectory);
end

equationIds = { ...
    'eq01', 'eq02', 'eq03', 'eq04', 'eq05', 'eq06', 'eq07', 'eq08', ...
    'eq09', 'eq10', 'eq11', 'eq12', 'eq13', 'eq14', 'eq15', 'eq16', ...
    'eq17', 'eq18', 'eq19', 'eq20', 'eq21', 'eq22'};

equations = { ...
    'a=\frac{L}{2},\qquad b=\frac{W}{2},\qquad c=\frac{H}{2}', ...
    'V_{\mathrm e}=\frac{4\pi abc}{3}=\frac{\pi LWH}{6},\qquad V_{\mathrm m}=\eta V_{\mathrm e}', ...
    'q(\mathbf d)=\left(\frac{d_x^{\mathrm b}}{a}\right)^2+\left(\frac{d_y^{\mathrm b}}{b}\right)^2+\left(\frac{d_z^{\mathrm b}}{c}\right)^2', ...
    '\mathbf r_{\mathrm c}(t)=\mathbf r_0+\mathbf R\left[vt,0,0\right]^{\mathrm T}', ...
    '\mathbf m_{\mathrm r}^{\mathrm b}=V_{\mathrm m}\mathbf M_{\mathrm r},\qquad \mathbf m_{\mathrm r}=\mathbf R\mathbf m_{\mathrm r}^{\mathrm b}', ...
    'N_i=\frac{abc}{2}\int_0^{\infty}\frac{\mathrm ds}{(s+a_i^2)\sqrt{(s+a^2)(s+b^2)(s+c^2)}},\qquad \sum_{i=1}^{3}N_i=1', ...
    '\chi=\mu_{\mathrm r}-1,\qquad \mathbf H_{\mathrm g}^{\mathrm b}=\frac{\mathbf R^{\mathrm T}\mathbf B_{\mathrm g}}{\mu_0}', ...
    'm_{\mathrm i,k}^{\mathrm b}=V_{\mathrm m}\frac{\chi H_{\mathrm g,k}^{\mathrm b}}{1+N_k\chi},\qquad \mathbf m_{\mathrm i}=\mathbf R\mathbf m_{\mathrm i}^{\mathrm b}', ...
    '\mathbf G(\mathbf r)=\frac{\mu_0}{4\pi r^3}\left(3\hat{\mathbf r}\hat{\mathbf r}^{\mathrm T}-\mathbf I_3\right)', ...
    '\mathbf B(\mathbf r)=\mathbf G(\mathbf r)\mathbf m=\frac{\mu_0}{4\pi r^3}\left[3(\mathbf m\cdot\hat{\mathbf r})\hat{\mathbf r}-\mathbf m\right]', ...
    '\delta_i^{\mathrm b}=\left[a\xi_i,b\nu_i,c\zeta_i\right]^{\mathrm T},\qquad \xi_i^2+\nu_i^2+\zeta_i^2<1', ...
    '\widetilde w_i=1-(\xi_i^2+\nu_i^2+\zeta_i^2),\qquad w_i=\frac{\widetilde w_i}{\sum_j\widetilde w_j},\qquad \sum_i w_i=1', ...
    '\mathbf G_{\mathrm{array}}(\mathbf r)=\sum_{i=1}^{N_{\mathrm a}}w_i\mathbf G\left(\mathbf r-\mathbf R\delta_i^{\mathrm b}\right)', ...
    '\mathbf G_{\mathrm{hybrid}}=\mathbf G_0+\alpha\left(\mathbf G_{\mathrm{array}}-\mathbf G_0\right),\qquad 0\leq\alpha\leq1', ...
    '\mathbf B_{\mathrm{static}}=\mathbf G_{\mathrm{hybrid}}\mathbf m_{\mathrm r},\qquad \mathbf B_{\mathrm{induced}}=\mathbf G_{\mathrm{hybrid}}\mathbf m_{\mathrm i}', ...
    '\mathbf B_{\mathrm{macro}}=\mathbf G_0(\mathbf m_{\mathrm r}+\mathbf m_{\mathrm i}),\qquad \Delta\mathbf B_{\mathrm{local}}=(\mathbf G_{\mathrm{hybrid}}-\mathbf G_0)(\mathbf m_{\mathrm r}+\mathbf m_{\mathrm i})', ...
    '\mathbf B_{\mathrm{target}}=\mathbf B_{\mathrm{macro}}+\Delta\mathbf B_{\mathrm{local}}=\mathbf B_{\mathrm{static}}+\mathbf B_{\mathrm{induced}}', ...
    '\mathbf B_{\mathrm{env}}=\mathbf B_{\mathrm{main}}+\mathbf B_{\mathrm{crust}}+\mathbf B_{\mathrm{fluct}}+\mathbf B_{\mathrm{local}}+\mathbf B_{\mathrm{motional}}', ...
    '\mathbf B_{\mathrm{sensor}}=\mathbf B_{\mathrm{target}}+\mathbf B_{\mathrm{env}}', ...
    '\Delta B_{\mathrm{scalar}}=\|\mathbf B_{\mathrm{sensor}}\|-\|\mathbf B_{\mathrm{env}}\|', ...
    'N=\left\lfloor Tf_{\mathrm s}\right\rfloor+1,\qquad t_k=t_{\mathrm{start}}+\frac{k}{f_{\mathrm s}},\qquad k=0,\ldots,N-1', ...
    '\frac{\|\Delta\mathbf B_{\mathrm{local}}\|}{\|\mathbf B_{\mathrm{macro}}\|}=\mathcal O\left(\frac{D^2}{r^2}\right),\qquad r\gg D'};

for equationIndex = 1:numel(equations)
    figureHandle = figure('Visible', 'off', 'Color', 'white', ...
        'Units', 'pixels', 'Position', [100, 100, 2400, 320]);
    axesHandle = axes(figureHandle, 'Position', [0, 0, 1, 1], ...
        'Visible', 'off', 'XLim', [0, 1], 'YLim', [0, 1]);
    text(axesHandle, 0.5, 0.5, ['$' equations{equationIndex} '$'], ...
        'Interpreter', 'latex', 'FontSize', 26, ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'Color', 'black');
    outputPath = fullfile(outputDirectory, [equationIds{equationIndex} '.png']);
    exportgraphics(figureHandle, outputPath, 'Resolution', 300, 'BackgroundColor', 'white');
    close(figureHandle);
end

fprintf('已渲染 %d 个 LaTeX 公式到 %s\n', numel(equations), outputDirectory);
